name: TryXcodeGen
fileGroups:
  - config
configFiles:
  Debug: config/Debug.xcconfig
  Release: config/Release.xcconfig
targets:
  TryXcodeGen:
    type: application
    platform: iOS
    sources: src
    configFiles:
      Debug: config/try_xcodegen-Debug.xcconfig
      Release: config/try_xcodegen-Release.xcconfig
    settings:
      base:
        INFOPLIST_FILE: src/resource/Info.plist
      CURRENT_PROJECT_VERSION: 1
    scheme:
      testTargets:
        - TryXcodeGenTests
  TryXcodeGenTests:
    type: bundle.unit-test
    platform: iOS
    sources: test
    configFiles:
      Debug: config/try_xcodegenTests-Debug.xcconfig
      Release: config/try_xcodegenTests-Release.xcconfig
    settings:
      base:
        INFOPLIST_FILE: test/resource/Info.plist
    dependencies:
      - target: TryXcodeGen
      